name: Auto Greeting Workflow

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Manual workflow"]
    types:
      - completed

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello, world!"
